### PR TITLE
Publish redox-css-model

### LINKED ISSUE #1: Create redox-css-model Bower package
- [x] Make a `bower.json`
- [x] Register with the public repository
- [x] Provide a license for the code

### LINKED ISSUE #2: Add initial set of atoms
These need to include all those required for the navigation bar redesign. However, a more comprehensive set is fine as well.

### LINKED ISSUE #3: Publish sitemap on gh-pages branch
This might be handy, but it's not really a priority.

### LINKED ISSUE #4: Setup build tooling for atom compiling
- [x] Create a `package.json` for npm package requirements
- [x] Create a `Gruntfile.js`
- [x] Copy over anything else needed from playground repo

### PR DESCRIPTION
**Pull request by luketurner**
This PR is for publishing the whole repository as version 1.0.0. Reviewer please look at the whole repository and post any comments or issues here.
Closes #1, 
Closes #2
Closes #3
Closes #4
Closes #5

### CODE REVIEW

**Comment by ajkitson** [comment]
Scott and LT have reviewed the content of the CSS. Could use a cursory pass for how we'll use it in our repo

**Comment by ajkitson** [comment]
Let's add some documentation on how to use this repo:
- How do you launch the style guide?
- When do you update the json files vs. the scss?
- What do you change in this repo vs. in the main repo?
- What is the prototyping workflow?
- Any other decisions you made in the course of putting this together

The code looks good and it's fun to play around with the style guide. Main concern is that you've put a lot of thought into how to work with this repo and the rest of us on the team won't know how to take advantage of the work you've done (and might inadvertently do something counter to what you decided).

**Comment by luketurner** [comment]
I updated the README to include more documentation about contributing, PRs, versioning, etc. Hit me up with any remaining obscurities, and I'll get them in there.

**Comment by luketurner** [comment]
This PR is outdated. The project is currently at version 0.3.0

**Pull request closed without merging**
